# Generated by Django 5.2.1 on 2025-05-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_meal_ingredients_alter_meal_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='many',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
