

services:
  web:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_web
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      # Bu yerda POSTGRES_* o'zgartirish shart emas, chunki bu faqat DB konteyneriga kerak
      # Django esa settings.py dan oladi

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: cloud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "root"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis

  celery:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_celery
    command: celery -A src worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery-beat:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_celery_beat
    command: celery -A src beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

volumes:
  postgres_data:
