# Generated by Django 5.2.1 on 2025-05-21 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_meal_many'),
        ('servings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servings',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.meal'),
        ),
    ]
