# Generated by Django 5.2.1 on 2025-05-19 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
        ('users', '0002_alter_user_managers_remove_user_password_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default='simple', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='roles.role'),
        ),
    ]
