# Generated by Django 5.2.1 on 2025-05-20 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerts',
            options={'ordering': ['-created_at'], 'verbose_name': 'Alert', 'verbose_name_plural': 'Alerts'},
        ),
    ]
