# Generated by Django 5.2.1 on 2025-05-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='kid',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol')], max_length=20),
        ),
    ]
