# Generated by Django 5.2.1 on 2025-05-24 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_kid_full_name_alter_kid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='group.group'),
        ),
    ]
